apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.name }}
  namespace: {{ .Values.namespaceValue }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volume.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claimName }}
  namespace: {{ .Values.namespaceValue }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.claimCapacity }}