apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.dbclaimname }}
  namespace: {{ .Values.namespaceValue }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.wpclaimname }}
  namespace: {{ .Values.namespaceValue }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}
