apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-mysql"
  namespace: {{ .Values.namespaceValue }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.dbport }}
  selector:
    app: {{ .Chart.Name }}
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-web"
  namespace: {{ .Values.namespaceValue }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ .Values.service.webport }}
  selector:
    app: {{ .Chart.Name }}
    tier: frontend
  type: LoadBalancer
