apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  namespace: website
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/kube/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-claim
  namespace: website
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
