apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
spec:
  selector:
    app: website
  ports:
    - port: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  template:
    metadata:
      labels:
        app: website
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-volume-claim
      containers:
      - name: website
        image: mmontuori/web-site:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: data
            mountPath: "/usr/share/nginx/html"

